apiVersion: v1
appVersion: "1.0.1"
description: A Helm chart for Kubernetes
name: app-example
version: 1.0.1
dependencies:
# TODO: Check, why next dependency is failing
- name: mongodb
  version: 13.5.0
  # repository: https://github.com/bitnami/charts/tree/main/bitnami/mongodb
  # repository: https://github.com/bitnami/charts/tree/main/bitnami
  # repository: https://github.com/bitnami/charts
  repository: https://github.com/bitnami
  tags:
    - mongodb
- name: mariadb
  version: 5.x.x
  repository: https://charts.helm.sh/stable
  condition: mariadb.enabled
  tags:
    - database
